version: '3.8'
services:
  redis:
    image: redis:7.4.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis/config/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf