version: '3'
services:
  nginx:
    image: nginx:1.27.5
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # 主配置文件挂载
      - ./data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      # 子配置文件目录
      - ./data/nginx/conf/conf.d:/etc/nginx/conf.d
      # 静态资源目录
      - ./data/nginx/html:/usr/share/nginx/html
      # 日志目录
      - ./data/nginx/logs:/var/log/nginx
      # SSL 证书目录
      - ./data/nginx/ssl:/etc/nginx/ssl
      # 自定义数据目录
      - ./data/nginx/data:/data
      # MIME 类型配置
      - ./data/nginx/conf/mime.types:/etc/nginx/mime.types