version: '3.8'
services:
  minio:
    # 2025-05-24 开始，除了社区版 Web 管理界面的所有核心管理功能（如权限配置、用户管理、存储桶策略设置等），仅保留基础的对象浏览功能。
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    ports:
      # api 端口
      - "9000:9000"
      # 控制台端口
      - "9001:9001"
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      # 管理后台用户名
      MINIO_ROOT_USER: root
      # 管理后台密码，最小 8 个字符
      MINIO_ROOT_PASSWORD: 12345678
      # https 需要指定域名
      #MINIO_SERVER_URL: "https://xxx.com:9000"
      #MINIO_BROWSER_REDIRECT_URL: "https://xxx.com:9001"
      # 开启压缩 on 开启 off 关闭
      MINIO_COMPRESS: "off"
      # 扩展名 .pdf,.doc 为空 所有类型均压缩
      MINIO_COMPRESS_EXTENSIONS: ""
      # mime 类型 application/pdf 为空 所有类型均压缩
      MINIO_COMPRESS_MIME_TYPES: ""
    volumes:
      # 映射当前目录下的 data 目录至容器内/data 目录
      - ./data/minio/data:/data
      # 映射配置目录
      - ./data/minio/config:/root/.minio/
    command: server --address ':9000' --console-address ':9001' /data  # 指定容器中的目录 /data
